version: '2'
services:

  mandrake-db:
    user: root
    image: mongo:latest
    restart: always
    command: ["mongod", "--smallfiles"]
    container_name: mandrake-db
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db:rw

  mandrake-connector:
    user: root
    build: .
    image: yantrashala/mandrake-connector
    restart: always
    container_name: mandrake-connector
    volumes:
      - ./config:/home/bot-connector/config:rw
    depends_on:
      - mandrake-db
    links:
      - mandrake-db
    environment:
      - SERVICE_NAME=mandrake-connector
      - NODE_ENV=developemnt
    ports:
      - "6060:6060"
    volumes:
      - ./doc:/home/bot-connector/doc:rw
    command: ["yarn", "start-dev"]
